// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

export type AllPhoneCallsModel = {
    CallSID?: string | null;
    CallTo?: string | null;
    CallFrom?: string | null;
    CreatedDate?: string;
    CallStatus?: string | null;
    CallDuration?: number | null;
    RecordingUrl?: string | null;
    CallFromName?: string | null;
    CallToName?: string | null;
    Direction?: CallDirection;
    NumberName?: string | null;
    Provider?: PhoneCallProvider;
    PhoneCallId?: number | null;
    UnifiedPhoneCallId?: number | null;
    CallType?: string | null;
    PhoneCallLeadId?: number | null;
    IsPrimary?: boolean;
    CallSummary?: string | null;
    CallTranscript?: string | null;
    TranscriptionPath?: string | null;
    AssociationId?: number | null;
    Reviewed?: boolean;
};

export type ApiHypermediaLink = {
    Rel?: string | null;
    Href?: string | null;
    Method?: string | null;
};

export type ApiLeadFile = {
    Id?: number | null;
    Name?: string | null;
    Url?: string | null;
    Message?: string | null;
};

export type ApiMessageAttachment = {
    Filename?: string | null;
    Base64Data?: string | null;
};

export type AssignUserApi = {
    LeadRoleId?: number;
    UserId?: number;
};

export type AudioCallProcessingStatus = 'NotStarted' | 'DataEnrichment' | 'AudioProcessing' | 'AudioTranscription' | 'Retrying' | 'Failed' | 'Completed';

export type BlobUrlResponseModel = {
    UploadUrl?: string | null;
    LeadId?: number | null;
    FileId?: number | null;
    Headers?: {
        [key: string]: string;
    } | null;
    readonly IsValid?: boolean;
    ErrorMessage?: string | null;
};

export type CallDirection = 'Inbound' | 'Outbound' | 'Unknown';

export type CallEventResponse = {
    Success?: boolean;
    ErrorMessage?: string | null;
    Timestamp?: string;
    Id?: number | null;
};

export type CaseTypeApi = {
    Id?: number;
    Name?: string | null;
    Code?: string | null;
    Description?: string | null;
};

export type ChangeLeadStatusApi = {
    Status: number;
    Substatus?: number | null;
    SubstatusReason?: string | null;
    SeverityLevel?: number | null;
    AssignUsers?: Array<AssignUserApi> | null;
    AppointmentDate?: string | null;
    AppointmentLocation?: string | null;
    ReferredToId?: number | null;
    ReferralGroupId?: number | null;
    Notes?: string | null;
};

export type CheckForRecentByPhoneModel = {
    readonly LeadAndOpportunityCount?: number;
    ContactCount?: number;
    LeadCount?: number;
    OpportunityCount?: number;
    IsCurrentClient?: boolean;
    LatestLeadCreatedDate?: string | null;
    LatestLeadUrl?: string | null;
    LatestLeadName?: string | null;
    LatestOpportunityCreatedDate?: string | null;
    LatestOpportunityUrl?: string | null;
    LatestOpportunityName?: string | null;
    SearchUrl?: string | null;
};

export type CollectionSectionApi = {
    Id?: number;
    Name?: string | null;
    Entries?: Array<CollectionSectionEntryApi> | null;
};

export type CollectionSectionDeleteApi = {
    EntryIds?: Array<number> | null;
};

export type CollectionSectionEntryApi = {
    Id?: number;
    CreatedDate?: string;
    Values?: Array<CollectionSectionFieldValueApi> | null;
};

export type CollectionSectionEntryUpdateApi = {
    Id?: number | null;
    Values?: Array<CollectionSectionValueUpdateApi> | null;
};

export type CollectionSectionFieldValueApi = {
    Id?: number;
    CustomFieldId?: number;
    FieldName?: string | null;
    Value?: string | null;
};

export type CollectionSectionUpdateApi = {
    Entries?: Array<CollectionSectionEntryUpdateApi> | null;
};

export type CollectionSectionValueUpdateApi = {
    CustomFieldId?: number;
    Value?: string | null;
};

export type ContactApi = {
    Id?: number;
    FirstName?: string | null;
    MiddleName?: string | null;
    LastName?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    County?: string | null;
    HomePhone?: string | null;
    MobilePhone?: string | null;
    WorkPhone?: string | null;
    Email?: string | null;
    PreferredContactMethod?: string | null;
    Birthdate?: string | null;
    Longitude?: string | null;
    Latitude?: string | null;
    SubscribeToMailingList?: boolean;
    BadAddress?: boolean;
    Deceased?: boolean | null;
    Gender?: string | null;
    Minor?: boolean | null;
    Language?: string | null;
    Code?: string | null;
    DoNotText?: boolean;
    CreatedOn?: string;
    CreatedBy?: string | null;
    CreatedById?: number;
    PendingGeocode?: boolean;
    LeadIds?: Array<number> | null;
    CustomFields?: Array<ContactCustomFieldsValueApi> | null;
    LastUpdatedDTM?: string;
    Tags?: Array<ContactTagApi> | null;
};

export type ContactCustomFieldsValueApi = {
    CustomFieldId?: number;
    Value?: string | null;
    Name?: string | null;
};

export type ContactMethods = 'MobilePhone' | 'HomePhone' | 'WorkPhone' | 'Email' | 'Text' | 'Mail';

export type ContactTagApi = {
    Id?: number;
    CreatedDate?: string;
    TagText?: string | null;
};

export type ContactUpdateApi = {
    FirstName: string;
    MiddleName?: string | null;
    LastName: string;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    County?: string | null;
    HomePhone?: string | null;
    MobilePhone?: string | null;
    WorkPhone?: string | null;
    Email?: string | null;
    PreferredContactMethod?: string | null;
    Birthdate?: string | null;
    SubscribeToMailingList?: boolean;
    BadAddress?: boolean;
    Deceased?: boolean | null;
    DeathDate?: string | null;
    Gender?: string | null;
    Minor?: boolean | null;
    Language?: string | null;
    Code?: string | null;
    DoNotText?: boolean;
};

export type CreateStatusRecipe = 'Standard' | 'Schedulable' | 'Sequenceable';

export type CustomDatatypes = 'Text' | 'TrueFalse' | 'DropDownList' | 'TextArea' | 'Date' | 'YesNo' | 'Currency' | 'Percentage' | 'Radio' | 'Checkbox' | 'Section' | 'Link' | 'FilevineContact' | 'FileUpload' | 'TextDescription' | 'SectionBreak' | 'Hidden' | 'Number' | 'Decimal' | 'CollectionSection' | 'AISummary' | 'WebhookTrigger' | 'Boolean' | 'DateOnly' | 'UnitTesting';

export type CustomFieldUpdateModel = {
    CustomFieldId?: number;
    CustomFieldValue?: string | null;
};

export type CustomFieldsApi = {
    Id?: number;
    FieldName?: string | null;
    Location?: string | null;
    Directions?: string | null;
    DisplayOrder?: number;
    DefaultValues?: string | null;
    Code?: string | null;
    CaseTypes?: Array<CaseTypeApi> | null;
    DependsOn?: number | null;
    FieldType?: string | null;
    Disabled?: boolean;
    ReadOnly?: boolean;
    Hidden?: boolean;
    Required?: boolean;
};

export type CustomFieldsUpdateApi = {
    Id?: number | null;
    Code?: string | null;
    CustomFields?: Array<CustomFieldUpdateModel> | null;
};

export type CustomFieldsValueApi = {
    CustomFieldId?: number;
    Value?: string | null;
    Name?: string | null;
};

export type EndExternalCallRequest = {
    ProviderName?: string | null;
    ProviderId?: string | null;
    Direction?: CallDirection;
    CallStatus?: string | null;
    StartCallDTM?: string | null;
    CallerNumber?: string | null;
    CallerName?: string | null;
    CallerCity?: string | null;
    CallerState?: string | null;
    CallerZip?: string | null;
    CallerCountry?: string | null;
    CalleeNumber?: string | null;
    ReferrerUrl?: string | null;
    keywords?: string | null;
    CurrentUrl?: string | null;
    utm_source?: string | null;
    medium?: string | null;
    utm_medium?: string | null;
    utm_term?: string | null;
    utm_content?: string | null;
    utm_campaign?: string | null;
    ga?: string | null;
    gclid?: string | null;
    fbclid?: string | null;
    msclkid?: string | null;
    campaign?: string | null;
    EndCallDTM?: string | null;
    DurationSeconds?: number | null;
    RecordingUrl?: string | null;
    TranscriptionText?: string | null;
    CallSummary?: string | null;
};

export type EsignDocumentApi = {
    Id?: number;
    EnvelopeId?: string | null;
    Title?: string | null;
    Status?: string | null;
    DateSent?: string | null;
    DateDelivered?: string | null;
    DateCompleted?: string | null;
    DateDeclined?: string | null;
    DateVoided?: string | null;
    EmailUsed?: string | null;
    NameUsed?: string | null;
    SentBy?: EsignSendTypes;
    PhoneUsed?: string | null;
    ContactId?: number | null;
};

export type EsignSendTypes = 'Unknown' | 'Email' | 'Sms';

export type ExpenseAddApi = {
    Amount: number;
    ExpenseDate: string;
    ExpenseDescription?: string | null;
    MarketingSourceId: number;
    CaseTypeId?: number | null;
    OfficeId?: number | null;
    Vendor: string;
};

export type ExpenseApi = {
    Id?: number;
    Amount?: number;
    ExpenseDate?: string;
    ExpenseDescription?: string | null;
    MarketingSourceId?: number | null;
    CaseTypeId?: number | null;
    OfficeId?: number | null;
    Vendor?: string | null;
};

export type ExternalPhoneCall = {
    Id?: number;
    ProviderName?: string | null;
    ProviderId?: string | null;
    CallSID?: string | null;
    StartCallDTM?: string | null;
    EndCallDTM?: string | null;
    Direction?: CallDirection;
    DurationSeconds?: number | null;
    CallerName?: string | null;
    CallerCity?: string | null;
    CallerState?: string | null;
    CallerCountry?: string | null;
    RecordingUrl?: string | null;
    ReferrerUrl?: string | null;
    Metadata?: string | null;
    CallTo?: string | null;
    CallFrom?: string | null;
    CallStatus?: string | null;
    ProcessingStatus?: AudioCallProcessingStatus;
    TranscriptionPath?: string | null;
    CallSummary?: string | null;
    CreatedDTM?: string;
    UpdatedDTM?: string;
    UTM?: string | null;
    Keywords?: string | null;
    Campaign?: string | null;
    ClientId?: string | null;
    ClickId?: string | null;
    CurrentUrl?: string | null;
};

export type FieldType = 'Lead' | 'Contact' | 'LeadRole' | 'Standard' | 'None' | 'LeadFormOther' | 'Status';

export type FormFieldListItem = {
    Text?: string | null;
    Value?: string | null;
    Disabled?: boolean;
};

export type LeadApi = {
    Id?: number;
    Summary?: string | null;
    InjuryInformation?: string | null;
    Status?: string | null;
    SubStatus?: string | null;
    SeverityLevel?: string | null;
    SeverityLevelId?: number;
    Code?: string | null;
    Contact?: ContactApi;
    PracticeArea?: CaseTypeApi;
    MarketingSource?: string | null;
    ContactSource?: string | null;
    TalkedToOtherAttorneys?: boolean | null;
    FoundUsNotes?: string | null;
    UTM?: string | null;
    CurrentUrl?: string | null;
    ReferringUrl?: string | null;
    ClickId?: string | null;
    ClientId?: string | null;
    Keywords?: string | null;
    Campaign?: string | null;
    AppointmentLocation?: string | null;
    Office?: string | null;
    OfficeCode?: string | null;
    MarketingCampaign?: string | null;
    MarketingCampaignKey?: string | null;
    ReferredTo?: ReferredToApi;
    ReferralGroupId?: number | null;
    ReferredByName?: string | null;
    ReferredBy?: ReferredByApi;
    CreatedDate?: string;
    IncidentDate?: string | null;
    AppointmentScheduledDate?: string | null;
    SignedUpDate?: string | null;
    CaseClosedDate?: string | null;
    ReferredDate?: string | null;
    LastStatusChangeDate?: string | null;
    SourceLeadId?: number | null;
    FilevineTeamIds?: string | null;
    Intake?: UserApi;
    Paralegal?: UserApi;
    Investigator?: UserApi;
    Attorney?: UserApi;
    AssignedTo?: Array<LeadRoleUserApi> | null;
    Creator?: UserApi;
    RelatedContacts?: Array<RelatedContactApi> | null;
    Messages?: Array<MessageApi> | null;
    Notes?: Array<LeadNoteApi> | null;
    Opportunity?: OpportunityLimitedApi;
    PhoneCall?: PhoneCallApi;
    Files?: Array<LeadFileApi> | null;
    CustomFields?: Array<CustomFieldsValueApi> | null;
    Settlements?: Array<SettlementApi> | null;
    LeadStatusHistory?: Array<LeadStatusHistoryApi> | null;
    CollectionSections?: Array<CollectionSectionApi> | null;
    PhoneCalls?: Array<AllPhoneCallsModel> | null;
    Tasks?: Array<TaskApi> | null;
    EsignDocuments?: Array<EsignDocumentApi> | null;
};

export type LeadApiFlat = {
    Id?: number;
    ContactId?: number;
    PhoneNumber?: string | null;
    MobilePhone?: string | null;
    HomePhone?: string | null;
    WorkPhone?: string | null;
    PreferredContactMethod?: ContactMethods;
    Email?: string | null;
    FirstName?: string | null;
    LastName?: string | null;
    StatusId?: number;
    StatusName?: string | null;
    SubStatusId?: number | null;
    SubStatusName?: string | null;
    CaseType?: string | null;
    Code?: string | null;
    LastStatusChangeDate?: string;
    LastUpdateDate?: string | null;
};

export type LeadApiFlatApiPagedResponse = {
    Page?: number;
    ItemsPerPage?: number;
    TotalRecordCount?: number;
    readonly TotalPages?: number;
    Records?: Array<LeadApiFlat> | null;
};

export type LeadCollectionSectionApi = {
    LeadId?: number;
    Sections?: Array<CollectionSectionApi> | null;
};

export type LeadFileApi = {
    Id?: number;
    FileUrl?: string | null;
    FileName?: string | null;
    UploadOn?: string;
};

export type LeadFileUploadApi = {
    TotalFilesSent?: number;
    readonly UploadSuccessCount?: number;
    UploadedFiles?: Array<ApiLeadFile> | null;
    FailedFiles?: Array<ApiLeadFile> | null;
    readonly UploadFailCount?: number;
};

export type LeadFormApi = {
    LeadFormId?: number;
    FormName?: string | null;
    CaseTypeId?: number;
    CaseTypeName?: string | null;
    Enabled?: boolean;
    CreatedDate?: string;
    CreatedById?: number;
    CreatedBy?: string | null;
    DaysToExpiration?: number;
};

export type LeadFormApiApiHypermedia = {
    Error?: string | null;
    readonly IsValid?: boolean;
    Data?: LeadFormApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type LeadFormCreateApi = {
    CaseTypeId: number;
    Enabled?: boolean;
    DaysToExpiration?: number;
};

export type LeadFormFieldAddApi = {
    LeadFormId?: number;
    FieldId: number;
    FieldNameOverride?: string | null;
    DirectionsOverride?: string | null;
    Required?: boolean | null;
    DisplayOrder?: number | null;
    Columns?: number | null;
    ReadOnly?: boolean | null;
    LayoutOption?: number | null;
};

export type LeadFormFieldApi = {
    LeadFormFieldId?: number;
    FieldId?: number;
    FieldType?: CustomDatatypes;
    LayoutOption?: SectionHeadingLayoutOption;
    DisplayOrder?: number;
    DisplayName?: string | null;
    DisplayNameOverride?: string | null;
    Directions?: string | null;
    Required?: boolean;
    ReadOnly?: boolean;
    Columns?: number;
    DependsOn?: number | null;
    DependsOnName?: string | null;
    DependsOnValue?: string | null;
    Value?: string | null;
    ListItems?: Array<FormFieldListItem> | null;
    AlwaysRequired?: boolean;
    AlwaysReadOnly?: boolean;
    RequiredHidden?: boolean;
    ReadOnlyHidden?: boolean;
    DirectionsHidden?: boolean;
    FormControlName?: string | null;
    readonly DisplayLabel?: string | null;
    CustomFieldType?: FieldType;
    readonly Values?: Array<string> | null;
    LeadFormId?: number;
};

export type LeadFormFieldApiApiHypermedia = {
    Error?: string | null;
    readonly IsValid?: boolean;
    Data?: LeadFormFieldApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type LeadFormFieldUpdateApi = {
    FieldId?: number | null;
    FieldNameOverride?: string | null;
    DirectionsOverride?: string | null;
    Required?: boolean | null;
    DisplayOrder?: number | null;
    Columns?: number | null;
    ReadOnly?: boolean | null;
    LayoutOption?: number | null;
};

export type LeadFormInvitationApi = {
    LeadFormId?: number;
    LeadId?: number;
    ContactId?: number;
    InvitationGuid?: string | null;
    InvitationUrl?: string | null;
    Status?: string | null;
    SentDate?: string;
    SentVia?: string | null;
    ExpirationDate?: string;
    LastViewedDate?: string | null;
    CreatedById?: number;
    ErrorMessage?: string | null;
};

export type LeadFormInvitationApiApiHypermedia = {
    Error?: string | null;
    readonly IsValid?: boolean;
    Data?: LeadFormInvitationApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type LeadFormUpdateApi = {
    CaseTypeId?: number | null;
    Enabled?: boolean | null;
    DaysToExpiration?: number | null;
};

export type LeadNoteAddApi = {
    Text: string;
    Summary?: string | null;
    IsUserNote?: boolean;
};

export type LeadNoteApi = {
    Id?: number;
    LeadId?: number;
    Note?: string | null;
    Summary?: string | null;
    CreatedOn?: string;
    CreatedBy?: string | null;
    IsUserNote?: string | null;
};

export type LeadNoteUpdateApi = {
    Text: string;
    Summary?: string | null;
};

export type LeadRelatedEntityTypeApi = 'Sources' | 'SeverityLevel' | 'PhoneCalls' | 'Office' | 'Opportunity' | 'Creator' | 'ReferredTo' | 'ReferredBy' | 'LeadStatusHistory' | 'RelatedContacts' | 'ContactCustomFields' | 'LeadCustomFields' | 'LeadNotes' | 'Tasks' | 'Messages' | 'LeadFiles' | 'EsignDocuments' | 'Settlements' | 'CollectionSectionEntries';

export type LeadRoleApi = {
    LeadRoleId?: number;
    RoleName?: string | null;
    IsOwner?: boolean;
    IsDefault?: boolean;
    PriorityOrder?: number;
};

export type LeadRoleStatusApi = {
    LeadRoleId?: number;
    VisibilityOnLead?: number;
};

export type LeadRoleStatusCreateApi = {
    LeadRoleId?: number;
    VisibilityOnLead?: number;
};

export type LeadRoleUserApi = {
    Id?: number;
    FirstName?: string | null;
    LastName?: string | null;
    Email?: string | null;
    Code?: string | null;
    Roles?: Array<LeadRoleApi> | null;
    Permissions?: Array<PermissionApi> | null;
    LeadRoleId?: number;
    RoleName?: string | null;
    IsOwner?: boolean;
};

export type LeadStatusHistoryApi = {
    Timestamp?: string;
    ChangedBy?: string | null;
    StatusId?: number;
    SubStatusId?: number | null;
    LeadStatus?: string | null;
    SubStatus?: string | null;
    SubstatusReason?: string | null;
    ReferredToName?: string | null;
    ReferredToAttn?: string | null;
};

export type LeadUpdateApi = {
    CaseTypeId?: number | null;
    Summary?: string | null;
    IncidentDate?: string | null;
    CreatedDate?: string | null;
    OfficeId?: number | null;
    SourceId?: number | null;
    ContactSourceId?: number | null;
    FoundUsNotes?: string | null;
    UTM?: string | null;
    ReferringUrl?: string | null;
    CurrentUrl?: string | null;
    ReferredBy?: string | null;
    ClientId?: string | null;
    ClickId?: string | null;
    Keywords?: string | null;
    Campaign?: string | null;
    TeamIDs?: Array<number> | null;
};

export type LookupTypes = 'LeadSource' | 'CaseType' | 'MarketingSource' | 'Statuses' | 'Offices' | 'Forms' | 'Tags' | 'PhoneNumbers';

export type MessageAddApi = {
    LeadId: number;
    SendFrom: string;
    SendTo: string;
    SendCC?: string | null;
    Subject: string;
    Body?: string | null;
    HtmlBody?: string | null;
    SendFromName?: string | null;
    Attachments?: Array<ApiMessageAttachment> | null;
};

export type MessageApi = {
    Id?: number | null;
    SendFrom?: string | null;
    SendTo?: string | null;
    SendCC?: string | null;
    Subject?: string | null;
    Body?: string | null;
    CreatedOn?: string;
    DueForSendingOn?: string | null;
    IsInbound?: boolean;
    HasBeenSent?: boolean;
};

export type OpportunityApi = {
    Id?: number;
    FirstName?: string | null;
    MiddleName?: string | null;
    LastName?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    HomePhone?: string | null;
    WorkPhone?: string | null;
    MobilePhone?: string | null;
    Email?: string | null;
    Gender?: string | null;
    Language?: string | null;
    Birthdate?: string | null;
    PreferredContactMethod?: ContactMethods;
    LeadStatus?: string | null;
    SubStatus?: string | null;
    Office?: string | null;
    MarketingSource?: string | null;
    MarketingSourceDetails?: string | null;
    ContactSource?: string | null;
    Summary?: string | null;
    InjuryInformation?: string | null;
    IncidentDate?: string | null;
    CreatedDate?: string | null;
    LeadId?: number | null;
    Note?: string | null;
    ReferredBy?: string | null;
    SeverityLevel?: number | null;
    County?: string | null;
    AppointmentLocation?: string | null;
    AppointmentScheduledDate?: string | null;
    Code?: string | null;
    ReferringUrl?: string | null;
    CurrentUrl?: string | null;
    UTM?: string | null;
    ClientId?: string | null;
    ClickId?: string | null;
    Keywords?: string | null;
    Campaign?: string | null;
    Processed?: boolean;
    ProcessedDate?: string | null;
    ProcessedByName?: string | null;
    OpportunityTypeId?: OpportunityType;
    DisregardReason?: string | null;
    IsBeingEdited?: boolean;
    CustomFields?: Array<CustomFieldsValueApi> | null;
    AssignedTo?: Array<LeadRoleUserApi> | null;
    ProcessedBy?: UserApi;
};

export type OpportunityApiFlat = {
    Id?: number;
    CreatedDate?: string | null;
    FirstName?: string | null;
    LastName?: string | null;
    MobilePhone?: string | null;
    HomePhone?: string | null;
    WorkPhone?: string | null;
    Email?: string | null;
    CaseType?: string | null;
    OpportunitySource?: string | null;
    MarketingSource?: string | null;
    Status?: string | null;
    IsBeingEdited?: boolean;
    Processed?: boolean;
    ProcessedDate?: string | null;
    ProcessedByName?: string | null;
    DisregardReason?: string | null;
    LeadId?: number | null;
    LastUpdateDate?: string | null;
};

export type OpportunityApiFlatApiPagedResponse = {
    Page?: number;
    ItemsPerPage?: number;
    TotalRecordCount?: number;
    readonly TotalPages?: number;
    Records?: Array<OpportunityApiFlat> | null;
};

export type OpportunityLimitedApi = {
    Id?: number;
    OpportunityName?: string | null;
    CreatedDate?: string | null;
    ProcessedDate?: string | null;
    ProcessedById?: number | null;
};

export type OpportunityType = 'ManualEntry' | 'WebForm' | 'WebChat' | 'PhoneCall' | 'AnsweringService' | 'Other' | 'LeadGenerationService' | 'TextMessage' | 'ReceptionForm' | 'Email' | 'ReferralForm';

export type PermissionApi = {
    Id?: number;
    Name?: string | null;
};

export type PhoneCallApi = {
    Id?: number;
    CallFrom?: string | null;
    CallTo?: string | null;
    CallSID?: string | null;
    Label?: string | null;
    RecordingUrl?: string | null;
    CreatedDate?: string | null;
    CallSummary?: string | null;
    CallTranscript?: string | null;
};

export type PhoneCallProvider = 'Native' | 'CallRail' | 'CTM' | 'Api' | 'Manual' | 'Unknown';

export type ReferralGroupApi = {
    Id?: number;
    GroupName?: string | null;
    ReferralGroupMembers?: Array<ReferralGroupMemberApi> | null;
};

export type ReferralGroupMemberApi = {
    ReferralSourceId?: number;
    FirmName?: string | null;
    City?: string | null;
    State?: string | null;
    PhoneNumber?: string | null;
    Attn?: string | null;
};

export type ReferralSourceAddApi = {
    Name: string;
    PracticeArea: string;
    PhoneNumber?: string | null;
    Attn?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    Enabled?: boolean;
    Code?: string | null;
    ExternalCode?: string | null;
    Incoming?: boolean;
    Outgoing?: boolean;
    Priority?: number | null;
    Notes?: string | null;
};

export type ReferralSourceApi = {
    Id?: number;
    Name?: string | null;
    Type?: string | null;
    Code?: string | null;
    ExternalCode?: string | null;
    PracticeArea?: string | null;
    readonly PracticeAreas?: Array<string> | null;
    PhoneNumber?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    Incoming?: boolean;
    Outgoing?: boolean;
    Priority?: number | null;
    Notes?: string | null;
    Attn?: string | null;
};

export type ReferredByApi = {
    Id?: number;
    Name?: string | null;
    Type?: string | null;
    Code?: string | null;
    readonly CityAndState?: string | null;
    PreferredContactMethod?: ContactMethods;
    TagsList?: Array<string> | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    HomePhone?: string | null;
    WorkPhone?: string | null;
    MobilePhone?: string | null;
    FullMailingAddress?: string | null;
};

export type ReferredSubstatusType = 'ReferredOther' | 'ReferredDeclined' | 'ReferredPending' | 'ReferredAccepted' | 'ReferredClosed' | 'ReferredSigned' | 'ReferredNoFollowUp' | 'ReferredShowToReferralPartners';

export type ReferredToApi = {
    Id?: number;
    Name?: string | null;
    Type?: string | null;
    Code?: string | null;
    readonly PracticeAreas?: Array<string> | null;
    PhoneNumber?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    Incoming?: boolean;
    Outgoing?: boolean;
    Priority?: number | null;
    Notes?: string | null;
    Attn?: string | null;
};

export type RelatedContactApi = {
    Relationship?: string | null;
    Notes?: string | null;
    IsPlaintiff?: boolean;
    ContactType?: string | null;
    PromotedLeadId?: number | null;
    Contact?: ContactApi;
};

export type ScheduleAppointmentApi = {
    Location: string;
    Date: string;
    Status?: number | null;
    Substatus?: number | null;
    AssignUsers?: Array<AssignUserApi> | null;
};

export type SectionHeadingLayoutOption = 'Heading1' | 'Heading2' | 'InfoMessage' | 'WarningMessage' | 'InfoBox' | 'WarningBox';

export type SendEmailMessageApi = {
    LeadId: number;
    SendFrom: string;
    SendFromName?: string | null;
    SendTo: string;
    SendCC?: string | null;
    Subject: string;
    Body: string;
};

export type SendTextMessageApi = {
    LeadId: number;
    SendFrom?: string | null;
    SendTo: string;
    Body: string;
};

export type SettingsOptions = {
    Name?: string | null;
    IsEnabled?: boolean;
};

export type SettlementAddApi = {
    LeadId: number;
    Fee: number;
    Date?: string | null;
    Amount?: number | null;
    Summary: string;
    ReferralFee?: number | null;
    Expenses?: number | null;
    Notes?: string | null;
};

export type SettlementApi = {
    Id?: number;
    LeadId?: number | null;
    Fee?: number | null;
    Date?: string | null;
    Amount?: number | null;
    Summary?: string | null;
    ReferralFee?: number | null;
    Expenses?: number | null;
    Notes?: string | null;
};

export type SortOrder = 'Ascending' | 'Descending';

export type StartExternalCallRequest = {
    ProviderName?: string | null;
    ProviderId?: string | null;
    Direction?: CallDirection;
    CallStatus?: string | null;
    StartCallDTM?: string | null;
    CallerNumber?: string | null;
    CallerName?: string | null;
    CallerCity?: string | null;
    CallerState?: string | null;
    CallerZip?: string | null;
    CallerCountry?: string | null;
    CalleeNumber?: string | null;
    ReferrerUrl?: string | null;
    keywords?: string | null;
    CurrentUrl?: string | null;
    utm_source?: string | null;
    medium?: string | null;
    utm_medium?: string | null;
    utm_term?: string | null;
    utm_content?: string | null;
    utm_campaign?: string | null;
    ga?: string | null;
    gclid?: string | null;
    fbclid?: string | null;
    msclkid?: string | null;
    campaign?: string | null;
};

export type StatusApi = {
    Id?: number;
    Status?: string | null;
    StatusName?: string | null;
    StatusScript?: string | null;
    IsClosed?: boolean;
    IsCurrentClient?: boolean;
    IsReferrable?: boolean;
    IsSequenced?: boolean;
    IsScheduleable?: boolean;
    IsIncludedInSearch?: boolean;
    IsValueEnabled?: boolean;
    IsOnDashboard?: boolean;
    IsResolved?: boolean;
    IsWanted?: boolean;
    DisplayOrder?: number;
    Substatuses?: Array<SubStatusApi> | null;
    LeadRoleStatuses?: Array<LeadRoleStatusApi> | null;
};

export type StatusApiApiHypermedia = {
    Error?: string | null;
    readonly IsValid?: boolean;
    Data?: StatusApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type StatusApiApiHypermediaListApiHypermedia = {
    Error?: string | null;
    readonly IsValid?: boolean;
    Data?: Array<StatusApiApiHypermedia> | null;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type StatusCreateApi = {
    LeadStatus: string;
    StatusScript?: string | null;
    IsIncludedInSearch?: boolean;
    IsOnDashboard?: boolean;
    IsWanted?: boolean;
    IsResolved?: boolean;
    DisplayOrder?: number | null;
    Substatuses?: Array<SubStatusCreateApi> | null;
    LeadRoleStatuses?: Array<LeadRoleStatusCreateApi> | null;
};

export type StatusCreateApiApiHypermedia = {
    Error?: string | null;
    readonly IsValid?: boolean;
    Data?: StatusCreateApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type StatusUpdateApi = {
    LeadStatus?: string | null;
    StatusScript?: string | null;
    IsIncludedInSearch?: boolean | null;
    IsOnDashboard?: boolean | null;
    IsWanted?: boolean | null;
    IsResolved?: boolean | null;
    DisplayOrder?: number | null;
};

export type SubStatusApi = {
    Id?: number;
    SubStatusName?: string | null;
    StatusScript?: string | null;
    Reasons?: string | null;
    IsClosed?: boolean;
    IsCurrentClient?: boolean;
    IsScheduleable?: boolean;
    IsIncludedInSearch?: boolean;
    IsValueEnabled?: boolean;
    IsOnDashboard?: boolean;
    IsResolved?: boolean;
    IsWanted?: boolean;
    ReferredType?: ReferredSubstatusType;
    DisplayOrder?: number;
};

export type SubStatusCreateApi = {
    SubStatusName: string;
    SubStatusScript?: string | null;
    Reasons?: string | null;
    IsIncludedInSearch?: boolean;
    IsOnDashboard?: boolean;
    IsWanted?: boolean;
    DisplayOrder?: number | null;
};

export type SubStatusUpdateApi = {
    SubStatusName?: string | null;
    SubStatusScript?: string | null;
    Reasons?: string | null;
    IsIncludedInSearch?: boolean | null;
    IsOnDashboard?: boolean | null;
    IsWanted?: boolean | null;
    DisplayOrder?: number | null;
};

export type TaskApi = {
    Id?: number;
    LeadId?: number;
    Summary?: string | null;
    TaskStartDate?: string | null;
    TaskCompletionDate?: string | null;
    UserAssigned?: number;
    TaskType?: string | null;
    Details?: string | null;
};

export type TaskCreateApi = {
    LeadId: number;
    Summary: string;
    TaskStartDate: string;
    UserAssigned: number;
    TaskType: string;
    Details?: string | null;
    AssociateWithEmail?: boolean;
};

export type TaskUpdateApi = {
    TaskId?: number;
    Summary?: string | null;
    TaskStartDate?: string | null;
    Completed?: boolean | null;
    UserAssigned?: number | null;
    TaskType?: string | null;
    Details?: string | null;
};

export type UserApi = {
    Id?: number;
    FirstName?: string | null;
    LastName?: string | null;
    Email?: string | null;
    Code?: string | null;
    Roles?: Array<LeadRoleApi> | null;
    Permissions?: Array<PermissionApi> | null;
};

export type BlobUrlResponseModelWritable = {
    UploadUrl?: string | null;
    LeadId?: number | null;
    FileId?: number | null;
    Headers?: {
        [key: string]: string;
    } | null;
    ErrorMessage?: string | null;
};

export type CheckForRecentByPhoneModelWritable = {
    ContactCount?: number;
    LeadCount?: number;
    OpportunityCount?: number;
    IsCurrentClient?: boolean;
    LatestLeadCreatedDate?: string | null;
    LatestLeadUrl?: string | null;
    LatestLeadName?: string | null;
    LatestOpportunityCreatedDate?: string | null;
    LatestOpportunityUrl?: string | null;
    LatestOpportunityName?: string | null;
    SearchUrl?: string | null;
};

export type LeadApiWritable = {
    Id?: number;
    Summary?: string | null;
    InjuryInformation?: string | null;
    Status?: string | null;
    SubStatus?: string | null;
    SeverityLevel?: string | null;
    SeverityLevelId?: number;
    Code?: string | null;
    Contact?: ContactApi;
    PracticeArea?: CaseTypeApi;
    MarketingSource?: string | null;
    ContactSource?: string | null;
    TalkedToOtherAttorneys?: boolean | null;
    FoundUsNotes?: string | null;
    UTM?: string | null;
    CurrentUrl?: string | null;
    ReferringUrl?: string | null;
    ClickId?: string | null;
    ClientId?: string | null;
    Keywords?: string | null;
    Campaign?: string | null;
    AppointmentLocation?: string | null;
    Office?: string | null;
    OfficeCode?: string | null;
    MarketingCampaign?: string | null;
    MarketingCampaignKey?: string | null;
    ReferredTo?: ReferredToApiWritable;
    ReferralGroupId?: number | null;
    ReferredByName?: string | null;
    ReferredBy?: ReferredByApiWritable;
    CreatedDate?: string;
    IncidentDate?: string | null;
    AppointmentScheduledDate?: string | null;
    SignedUpDate?: string | null;
    CaseClosedDate?: string | null;
    ReferredDate?: string | null;
    LastStatusChangeDate?: string | null;
    SourceLeadId?: number | null;
    FilevineTeamIds?: string | null;
    Intake?: UserApi;
    Paralegal?: UserApi;
    Investigator?: UserApi;
    Attorney?: UserApi;
    AssignedTo?: Array<LeadRoleUserApi> | null;
    Creator?: UserApi;
    RelatedContacts?: Array<RelatedContactApi> | null;
    Messages?: Array<MessageApi> | null;
    Notes?: Array<LeadNoteApi> | null;
    Opportunity?: OpportunityLimitedApi;
    PhoneCall?: PhoneCallApi;
    Files?: Array<LeadFileApi> | null;
    CustomFields?: Array<CustomFieldsValueApi> | null;
    Settlements?: Array<SettlementApi> | null;
    LeadStatusHistory?: Array<LeadStatusHistoryApi> | null;
    CollectionSections?: Array<CollectionSectionApi> | null;
    PhoneCalls?: Array<AllPhoneCallsModel> | null;
    Tasks?: Array<TaskApi> | null;
    EsignDocuments?: Array<EsignDocumentApi> | null;
};

export type LeadApiFlatApiPagedResponseWritable = {
    Page?: number;
    ItemsPerPage?: number;
    TotalRecordCount?: number;
    Records?: Array<LeadApiFlat> | null;
};

export type LeadFileUploadApiWritable = {
    TotalFilesSent?: number;
    UploadedFiles?: Array<ApiLeadFile> | null;
    FailedFiles?: Array<ApiLeadFile> | null;
};

export type LeadFormApiApiHypermediaWritable = {
    Error?: string | null;
    Data?: LeadFormApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type LeadFormFieldApiWritable = {
    LeadFormFieldId?: number;
    FieldId?: number;
    FieldType?: CustomDatatypes;
    LayoutOption?: SectionHeadingLayoutOption;
    DisplayOrder?: number;
    DisplayName?: string | null;
    DisplayNameOverride?: string | null;
    Directions?: string | null;
    Required?: boolean;
    ReadOnly?: boolean;
    Columns?: number;
    DependsOn?: number | null;
    DependsOnName?: string | null;
    DependsOnValue?: string | null;
    Value?: string | null;
    ListItems?: Array<FormFieldListItem> | null;
    AlwaysRequired?: boolean;
    AlwaysReadOnly?: boolean;
    RequiredHidden?: boolean;
    ReadOnlyHidden?: boolean;
    DirectionsHidden?: boolean;
    FormControlName?: string | null;
    CustomFieldType?: FieldType;
    LeadFormId?: number;
};

export type LeadFormFieldApiApiHypermediaWritable = {
    Error?: string | null;
    Data?: LeadFormFieldApiWritable;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type LeadFormInvitationApiApiHypermediaWritable = {
    Error?: string | null;
    Data?: LeadFormInvitationApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type OpportunityApiFlatApiPagedResponseWritable = {
    Page?: number;
    ItemsPerPage?: number;
    TotalRecordCount?: number;
    Records?: Array<OpportunityApiFlat> | null;
};

export type ReferralSourceApiWritable = {
    Id?: number;
    Name?: string | null;
    Type?: string | null;
    Code?: string | null;
    ExternalCode?: string | null;
    PracticeArea?: string | null;
    PhoneNumber?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    Incoming?: boolean;
    Outgoing?: boolean;
    Priority?: number | null;
    Notes?: string | null;
    Attn?: string | null;
};

export type ReferredByApiWritable = {
    Id?: number;
    Name?: string | null;
    Type?: string | null;
    Code?: string | null;
    PreferredContactMethod?: ContactMethods;
    TagsList?: Array<string> | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    HomePhone?: string | null;
    WorkPhone?: string | null;
    MobilePhone?: string | null;
    FullMailingAddress?: string | null;
};

export type ReferredToApiWritable = {
    Id?: number;
    Name?: string | null;
    Type?: string | null;
    Code?: string | null;
    PhoneNumber?: string | null;
    Address1?: string | null;
    Address2?: string | null;
    City?: string | null;
    State?: string | null;
    Zip?: string | null;
    Email?: string | null;
    Incoming?: boolean;
    Outgoing?: boolean;
    Priority?: number | null;
    Notes?: string | null;
    Attn?: string | null;
};

export type StatusApiApiHypermediaWritable = {
    Error?: string | null;
    Data?: StatusApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type StatusApiApiHypermediaListApiHypermediaWritable = {
    Error?: string | null;
    Data?: Array<StatusApiApiHypermediaWritable> | null;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type StatusCreateApiApiHypermediaWritable = {
    Error?: string | null;
    Data?: StatusCreateApi;
    Actions?: Array<ApiHypermediaLink> | null;
    Links?: Array<ApiHypermediaLink> | null;
};

export type CollectionSectionsListData = {
    body?: never;
    path: {
        /**
         * ID of the Lead
         */
        leadId: number;
    };
    query?: never;
    url: '/api/leads/{leadId}/collectionsections';
};

export type CollectionSectionsListResponses = {
    /**
     * OK
     */
    200: LeadCollectionSectionApi;
};

export type CollectionSectionsListResponse = CollectionSectionsListResponses[keyof CollectionSectionsListResponses];

export type CollectionSectionsDeleteData = {
    /**
     * list of entry IDs to delete; lookup via GET endpoint
     */
    body: CollectionSectionDeleteApi;
    path: {
        /**
         * ID of the Lead
         */
        leadId: number;
        /**
         * ID of the Collection Section
         */
        sectionId: number;
    };
    query?: never;
    url: '/api/leads/{leadId}/collectionsections/{sectionId}';
};

export type CollectionSectionsDeleteResponses = {
    /**
     * OK
     */
    200: LeadCollectionSectionApi;
};

export type CollectionSectionsDeleteResponse = CollectionSectionsDeleteResponses[keyof CollectionSectionsDeleteResponses];

export type CollectionSectionsUpdateData = {
    /**
     * list of entries to update
     */
    body: CollectionSectionUpdateApi;
    path: {
        /**
         * ID of the Lead
         */
        leadId: number;
        /**
         * ID of the Collection Section
         */
        sectionId: number;
    };
    query?: never;
    url: '/api/leads/{leadId}/collectionsections/{sectionId}';
};

export type CollectionSectionsUpdateResponses = {
    /**
     * OK
     */
    200: LeadCollectionSectionApi;
};

export type CollectionSectionsUpdateResponse = CollectionSectionsUpdateResponses[keyof CollectionSectionsUpdateResponses];

export type CollectionSectionsAddData = {
    /**
     * list of entries to insert
     */
    body: CollectionSectionUpdateApi;
    path: {
        /**
         * ID of the Lead
         */
        leadId: number;
        /**
         * ID of the Collection Section
         */
        sectionId: number;
    };
    query?: never;
    url: '/api/leads/{leadId}/collectionsections/{sectionId}';
};

export type CollectionSectionsAddResponses = {
    /**
     * OK
     */
    200: LeadCollectionSectionApi;
};

export type CollectionSectionsAddResponse = CollectionSectionsAddResponses[keyof CollectionSectionsAddResponses];

export type ContactCustomFieldsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/contactcustomfields/list';
};

export type ContactCustomFieldsGetResponses = {
    /**
     * OK
     */
    200: Array<CustomFieldsApi>;
};

export type ContactCustomFieldsGetResponse = ContactCustomFieldsGetResponses[keyof ContactCustomFieldsGetResponses];

export type ContactsGetByIdData = {
    body?: never;
    path: {
        /**
         * Lead Docket Contact ID
         */
        id: number;
    };
    query?: never;
    url: '/api/contacts/{id}';
};

export type ContactsGetByIdResponses = {
    /**
     * OK
     */
    200: ContactApi;
};

export type ContactsGetByIdResponse = ContactsGetByIdResponses[keyof ContactsGetByIdResponses];

export type ContactsUpdateData = {
    /**
     * JSON model of contact details to update
     */
    body: ContactUpdateApi;
    path: {
        /**
         * Lead Docket Contact ID
         */
        id: number;
    };
    query?: never;
    url: '/api/contacts/{id}';
};

export type ContactsUpdateResponses = {
    /**
     * OK
     */
    200: ContactApi;
};

export type ContactsUpdateResponse = ContactsUpdateResponses[keyof ContactsUpdateResponses];

export type ContactsGetByCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Case Tracker Code
         */
        code: string;
    };
    url: '/api/contacts/getbycode';
};

export type ContactsGetByCodeResponses = {
    /**
     * OK
     */
    200: ContactApi;
};

export type ContactsGetByCodeResponse = ContactsGetByCodeResponses[keyof ContactsGetByCodeResponses];

export type ContactsSearchData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Search Term
         */
        searchTerm: string;
    };
    url: '/api/contacts/search';
};

export type ContactsSearchResponses = {
    /**
     * OK
     */
    200: Array<ContactApi>;
};

export type ContactsSearchResponse = ContactsSearchResponses[keyof ContactsSearchResponses];

export type ContactsUpdatecodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lead Docket Contact ID
         */
        id: number;
        /**
         * Case Tracker Code from external system
         */
        externalId: string;
    };
    url: '/api/contacts/updatecode';
};

export type ContactsUpdatecodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ContactsPutUpdateCustomFieldsData = {
    /**
     * JSON model of contact custom fields
     */
    body: CustomFieldsUpdateApi;
    path?: never;
    query?: never;
    url: '/api/contacts/updatecustomfields';
};

export type ContactsPutUpdateCustomFieldsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ContactsAddData = {
    /**
     * JSON model of contact details to add
     */
    body: ContactUpdateApi;
    path?: never;
    query?: never;
    url: '/api/contacts';
};

export type ContactsAddResponses = {
    /**
     * OK
     */
    200: ContactApi;
};

export type ContactsAddResponse = ContactsAddResponses[keyof ContactsAddResponses];

export type ContactsRecentByPhoneData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Phone Number
         */
        phone: string;
    };
    url: '/api/contacts/checkforrecentbyphone';
};

export type ContactsRecentByPhoneResponses = {
    /**
     * OK
     */
    200: Array<CheckForRecentByPhoneModel>;
};

export type ContactsRecentByPhoneResponse = ContactsRecentByPhoneResponses[keyof ContactsRecentByPhoneResponses];

export type LeadsGetByLastUpdatedSinceData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Contacts updated since this date.
         */
        date: string;
        /**
         * Page of the record set. Defaults to 1 if not specified.
         */
        page?: number;
        /**
         * Number of items per page request. Maximum is 500, defaults to 500 if not specified.
         */
        itemsPerPage?: number;
        /**
         * Order by Last Updated ascending or descending.
         */
        sortOrder?: SortOrder;
    };
    url: '/api/contacts/lastupdatedsince';
};

export type LeadsGetByLastUpdatedSinceResponses = {
    /**
     * OK
     */
    200: LeadApiFlatApiPagedResponse;
};

export type LeadsGetByLastUpdatedSinceResponse = LeadsGetByLastUpdatedSinceResponses[keyof LeadsGetByLastUpdatedSinceResponses];

export type ContactsAddTagData = {
    body?: never;
    path: {
        /**
         * Lead Docket Contact ID
         */
        id: number;
        /**
         * Tag ID to add
         */
        tagId: number;
    };
    query?: never;
    url: '/api/contacts/{id}/tags/{tagId}';
};

export type ContactsAddTagResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ContactsDeleteTagData = {
    body?: never;
    path: {
        /**
         * Lead Docket Contact ID
         */
        id: number;
        /**
         * Contact Tag ID
         */
        contactTagId: number;
    };
    query?: never;
    url: '/api/contacts/{id}/tags/{contactTagId}';
};

export type ContactsDeleteTagResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type CustomFieldsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/customfields/list';
};

export type CustomFieldsGetResponses = {
    /**
     * OK
     */
    200: Array<CustomFieldsApi>;
};

export type CustomFieldsGetResponse = CustomFieldsGetResponses[keyof CustomFieldsGetResponses];

export type GetExpenseData = {
    body?: never;
    path: {
        /**
         * Expense Id
         */
        id: number;
    };
    query?: never;
    url: '/api/expenses/{id}';
};

export type GetExpenseResponses = {
    /**
     * OK
     */
    200: ExpenseApi;
};

export type GetExpenseResponse = GetExpenseResponses[keyof GetExpenseResponses];

export type GetExpensesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Start of range
         */
        startdate?: string;
        /**
         * End of range
         */
        enddate?: string;
    };
    url: '/api/expenses/getlist';
};

export type GetExpensesResponses = {
    /**
     * OK
     */
    200: ExpenseApi;
};

export type GetExpensesResponse = GetExpensesResponses[keyof GetExpensesResponses];

export type AddExpenseData = {
    /**
     * The Expense information. Office is optional.
     */
    body: ExpenseAddApi;
    path?: never;
    query?: never;
    url: '/api/expenses';
};

export type AddExpenseResponses = {
    /**
     * Created
     */
    201: ExpenseApi;
};

export type AddExpenseResponse = AddExpenseResponses[keyof AddExpenseResponses];

export type ExpensesDeleteData = {
    body?: never;
    path: {
        /**
         * ID of the Expense to delete
         */
        id: number;
    };
    query?: never;
    url: '/api/expenses/delete/{id}';
};

export type ExpensesDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ExternalCallsStartData = {
    body: StartExternalCallRequest;
    path?: never;
    query?: never;
    url: '/api/externalcalls/start';
};

export type ExternalCallsStartErrors = {
    /**
     * Invalid request data
     */
    400: CallEventResponse;
    /**
     * Internal server error
     */
    500: CallEventResponse;
};

export type ExternalCallsStartError = ExternalCallsStartErrors[keyof ExternalCallsStartErrors];

export type ExternalCallsStartResponses = {
    /**
     * Call started successfully
     */
    200: CallEventResponse;
};

export type ExternalCallsStartResponse = ExternalCallsStartResponses[keyof ExternalCallsStartResponses];

export type ExternalCallsEndData = {
    body: EndExternalCallRequest;
    path?: never;
    query?: never;
    url: '/api/externalcalls/end';
};

export type ExternalCallsEndErrors = {
    /**
     * Invalid request data
     */
    400: CallEventResponse;
    /**
     * Call not found
     */
    404: CallEventResponse;
    /**
     * Internal server error
     */
    500: CallEventResponse;
};

export type ExternalCallsEndError = ExternalCallsEndErrors[keyof ExternalCallsEndErrors];

export type ExternalCallsEndResponses = {
    /**
     * Call ended successfully
     */
    200: CallEventResponse;
};

export type ExternalCallsEndResponse = ExternalCallsEndResponses[keyof ExternalCallsEndResponses];

export type ExternalCallsGetByIdData = {
    body?: never;
    path: {
        /**
         * Unified phone call ID
         */
        id: number;
    };
    query?: never;
    url: '/api/externalcalls/{id}';
};

export type ExternalCallsGetByIdErrors = {
    /**
     * Call not found
     */
    404: unknown;
};

export type ExternalCallsGetByIdResponses = {
    /**
     * Call details
     */
    200: ExternalPhoneCall;
};

export type ExternalCallsGetByIdResponse = ExternalCallsGetByIdResponses[keyof ExternalCallsGetByIdResponses];

export type ExternalCallsGetRecordingData = {
    body?: never;
    path: {
        /**
         * External phone call ID
         */
        id: number;
    };
    query?: never;
    url: '/api/externalcalls/{id}/recording';
};

export type ExternalCallsGetRecordingErrors = {
    /**
     * Call or recording not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ExternalCallsGetRecordingResponses = {
    /**
     * Recording file
     */
    200: unknown;
};

export type ExternalCallsGetTranscriptionData = {
    body?: never;
    path: {
        /**
         * External phone call ID
         */
        id: number;
    };
    query?: never;
    url: '/api/externalcalls/{id}/transcription';
};

export type ExternalCallsGetTranscriptionErrors = {
    /**
     * Call or transcription not found
     */
    404: unknown;
    /**
     * Internal server error
     */
    500: unknown;
};

export type ExternalCallsGetTranscriptionResponses = {
    /**
     * Transcription text file
     */
    200: unknown;
};

export type LeadFormsGetLeadFormInvitationData = {
    body?: never;
    path: {
        /**
         * Lead ID
         */
        leadId: number;
    };
    query?: never;
    url: '/api/leads/{leadId}/forms';
};

export type LeadFormsGetLeadFormInvitationResponses = {
    /**
     * OK
     */
    200: LeadFormInvitationApiApiHypermedia;
};

export type LeadFormsGetLeadFormInvitationResponse = LeadFormsGetLeadFormInvitationResponses[keyof LeadFormsGetLeadFormInvitationResponses];

export type LeadFormsCreateLeadFormInvitationData = {
    body?: never;
    path: {
        /**
         * Lead ID
         */
        leadId: number;
    };
    query?: {
        /**
         * contact method to send the invitation; if not specified, uses Email
         */
        contactMethod?: ContactMethods;
    };
    url: '/api/leads/{leadId}/forms';
};

export type LeadFormsCreateLeadFormInvitationResponses = {
    /**
     * Created
     */
    201: LeadFormInvitationApiApiHypermedia;
};

export type LeadFormsCreateLeadFormInvitationResponse = LeadFormsCreateLeadFormInvitationResponses[keyof LeadFormsCreateLeadFormInvitationResponses];

export type LeadFormsGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leads/forms';
};

export type LeadFormsGetAllResponses = {
    /**
     * OK
     */
    200: Array<LeadFormApiApiHypermedia>;
};

export type LeadFormsGetAllResponse = LeadFormsGetAllResponses[keyof LeadFormsGetAllResponses];

export type LeadFormsCreateData = {
    /**
     * details to populate the new LeadForm. `FormName` and `CaseTypeId` are required.
     */
    body: LeadFormCreateApi;
    path?: never;
    query?: never;
    url: '/api/leads/forms';
};

export type LeadFormsCreateResponses = {
    /**
     * Created
     */
    201: LeadFormApiApiHypermedia;
};

export type LeadFormsCreateResponse = LeadFormsCreateResponses[keyof LeadFormsCreateResponses];

export type LeadFormsDeleteData = {
    body?: never;
    path: {
        /**
         * ID of the LeadForm to delete
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/forms/{id}';
};

export type LeadFormsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadFormsGetByIdData = {
    body?: never;
    path: {
        /**
         * ID of the LeadForm
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/forms/{id}';
};

export type LeadFormsGetByIdResponses = {
    /**
     * OK
     */
    200: LeadFormApiApiHypermedia;
};

export type LeadFormsGetByIdResponse = LeadFormsGetByIdResponses[keyof LeadFormsGetByIdResponses];

export type LeadFormsUpdateData = {
    /**
     * details to update on the LeadForm. note - only the data provided will be updated.
     */
    body: LeadFormUpdateApi;
    path: {
        /**
         * ID of the LeadForm
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/forms/{id}';
};

export type LeadFormsUpdateResponses = {
    /**
     * OK
     */
    200: LeadFormApiApiHypermedia;
};

export type LeadFormsUpdateResponse = LeadFormsUpdateResponses[keyof LeadFormsUpdateResponses];

export type LeadFormsAddFieldData = {
    /**
     * details to populate on the new LeadFormField. `FieldId` is required.
     */
    body: LeadFormFieldAddApi;
    path: {
        /**
         * ID of the LeadForm to add the field to
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/forms/{id}/field';
};

export type LeadFormsAddFieldResponses = {
    /**
     * OK
     */
    200: LeadFormFieldApiApiHypermedia;
};

export type LeadFormsAddFieldResponse = LeadFormsAddFieldResponses[keyof LeadFormsAddFieldResponses];

export type LeadFormsDeleteFieldData = {
    body?: never;
    path: {
        /**
         * ID of the LeadForm
         */
        id: number;
        /**
         * ID of the LeadFormField to delete
         */
        fieldId: number;
    };
    query?: never;
    url: '/api/leads/forms/{id}/field/{fieldId}';
};

export type LeadFormsDeleteFieldResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadFormsUpdateFieldData = {
    /**
     * details to update on the LeadFormField. note - only the data provided will be updated.
     */
    body: LeadFormFieldUpdateApi;
    path: {
        /**
         * ID of the LeadForm
         */
        id: number;
        /**
         * ID of the LeadFormField to update
         */
        fieldId: number;
    };
    query?: never;
    url: '/api/leads/forms/{id}/field/{fieldId}';
};

export type LeadFormsUpdateFieldResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadFormsDeleteFieldsData = {
    body?: never;
    path: {
        /**
         * ID of the LeadForm
         */
        id: number;
    };
    query: {
        /**
         * FieldType of the fields to delete (`Lead` and `Contact` are custom fields)
         */
        fieldType: FieldType;
    };
    url: '/api/leads/forms/{id}/fields';
};

export type LeadFormsDeleteFieldsResponses = {
    /**
     * OK
     */
    200: Array<number>;
};

export type LeadFormsDeleteFieldsResponse = LeadFormsDeleteFieldsResponses[keyof LeadFormsDeleteFieldsResponses];

export type GetApiLeadrolesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leadroles';
};

export type GetApiLeadrolesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadRoleDeleteData = {
    body?: never;
    path: {
        /**
         * ID of the Lead Role to delete
         */
        id: number;
    };
    query?: never;
    url: '/api/leadroles/{id}';
};

export type LeadRoleDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsGetByStatusData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The status ID for the Leads to get.
         */
        status?: number;
        /**
         * Optional comma separated list of sub statuses to get.
         */
        subStatusIds?: string;
        /**
         * Page of the record set. Defaults to 1 if not specified.
         */
        page?: number;
        /**
         * Number of items per paged request. Maximum is 500, defaults to 500 if not specified.
         */
        itemsPerPage?: number;
        /**
         * Order by Last Status Change Date ascending or descending
         */
        sortOrder?: SortOrder;
    };
    url: '/api/leads';
};

export type LeadsGetByStatusResponses = {
    /**
     * OK
     */
    200: LeadApiFlatApiPagedResponse;
};

export type LeadsGetByStatusResponse = LeadsGetByStatusResponses[keyof LeadsGetByStatusResponses];

export type LeadsGetByIdData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/{id}';
};

export type LeadsGetByIdResponses = {
    /**
     * OK
     */
    200: LeadApi;
};

export type LeadsGetByIdResponse = LeadsGetByIdResponses[keyof LeadsGetByIdResponses];

export type LeadUpdateData = {
    /**
     * details to update on the LeadDocket.Core.Models.Lead. note - only the data provided will be updated.
     */
    body: LeadUpdateApi;
    path: {
        /**
         * ID of the LeadDocket.Core.Models.Lead
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/{id}';
};

export type LeadUpdateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsGetBasicByIdData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/basic/{id}';
};

export type LeadsGetBasicByIdResponses = {
    /**
     * OK
     */
    200: LeadApi;
};

export type LeadsGetBasicByIdResponse = LeadsGetBasicByIdResponses[keyof LeadsGetBasicByIdResponses];

export type LeadsGetDetailedByIdData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        id: number;
    };
    query?: {
        /**
         * Bitwise flags indicating which related entities to include.
         * Please opt into the specific details you require.
         * Possible values (combine using bitwise OR):
         *
         * | Flag                                      | Description
         * |-------------------------------------------|-------------------------------------------------------------
         * | Sources                                   | Include lead source information.
         * | SeverityLevel                             | Include severity level information.
         * | PhoneCalls                                | Include phone call information.
         * | Office                                    | Include office information.
         * | Opportunity                               | Include opportunity information.
         * | Creator                                   | Include lead creator information.
         * | ReferredTo                                | Include referred to contact information.
         * | ReferredBy                                | Include referred by contact information.
         * | LeadStatusHistory                         | Include lead status history.
         * | RelatedContacts                           | Include related contacts.
         * | ContactCustomFields                       | Include contact custom fields.
         * | LeadCustomFields                          | Include lead custom fields.
         * | LeadNotes                                 | Include lead notes.
         * | Tasks                                     | Include tasks.
         * | Messages                                  | Include messages.
         * | LeadFiles                                 | Include lead files.
         * | EsignDocuments                            | Include esign documents.
         * | Settlements                               | Include settlements.
         * | CollectionSectionEntries                  | Include collection section entries.
         */
        flags?: Array<LeadRelatedEntityTypeApi>;
    };
    url: '/api/leads/detailed/{id}';
};

export type LeadsGetDetailedByIdResponses = {
    /**
     * OK
     */
    200: LeadApi;
};

export type LeadsGetDetailedByIdResponse = LeadsGetDetailedByIdResponses[keyof LeadsGetDetailedByIdResponses];

export type LeadsGetByCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Case Tracker Code
         */
        code: string;
    };
    url: '/api/leads/getbycode';
};

export type LeadsGetByCodeResponses = {
    /**
     * OK
     */
    200: LeadApi;
};

export type LeadsGetByCodeResponse = LeadsGetByCodeResponses[keyof LeadsGetByCodeResponses];

export type LeadsGetByOpportunityIdData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Opportunity Id
         */
        opportunityId: number;
    };
    url: '/api/leads/getbyopportunityid';
};

export type LeadsGetByOpportunityIdResponses = {
    /**
     * OK
     */
    200: LeadApi;
};

export type LeadsGetByOpportunityIdResponse = LeadsGetByOpportunityIdResponses[keyof LeadsGetByOpportunityIdResponses];

export type LeadsGetPendingExportData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leads/pendingexportids';
};

export type LeadsGetPendingExportResponses = {
    /**
     * OK
     */
    200: Array<number>;
};

export type LeadsGetPendingExportResponse = LeadsGetPendingExportResponses[keyof LeadsGetPendingExportResponses];

export type LeadsGetByLastStatusChangeSinceData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Leads with a status change since this date
         */
        date: string;
        /**
         * Page of the record set. Defaults to 1 if not specified.
         */
        page?: number;
        /**
         * Number of items per paged request. Maximum is 500, defaults to 500 if not specified.
         */
        itemsPerPage?: number;
        /**
         * Order by Last Status Change Date ascending or descending
         */
        sortOrder?: SortOrder;
    };
    url: '/api/leads/laststatuschangesince';
};

export type LeadsGetByLastStatusChangeSinceResponses = {
    /**
     * OK
     */
    200: LeadApiFlatApiPagedResponse;
};

export type LeadsGetByLastStatusChangeSinceResponse = LeadsGetByLastStatusChangeSinceResponses[keyof LeadsGetByLastStatusChangeSinceResponses];

export type LeadsGetByLastUpdatedSince2Data = {
    body?: never;
    path?: never;
    query: {
        /**
         * Leads updated since this date
         */
        date: string;
        /**
         * Page of the record set. Defaults to 1 if not specified.
         */
        page?: number;
        /**
         * Number of items per paged request. Maximum is 500, defaults to 500 if not specified.
         */
        itemsPerPage?: number;
        /**
         * Order by Last Updated ascending or descending
         */
        sortOrder?: SortOrder;
    };
    url: '/api/leads/lastupdatedsince';
};

export type LeadsGetByLastUpdatedSince2Responses = {
    /**
     * OK
     */
    200: LeadApiFlatApiPagedResponse;
};

export type LeadsGetByLastUpdatedSince2Response = LeadsGetByLastUpdatedSince2Responses[keyof LeadsGetByLastUpdatedSince2Responses];

export type LeadsPutUpdateCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lead Docket Lead ID
         */
        id: number;
        /**
         * Case Tracker Code from external system
         */
        externalId: string;
    };
    url: '/api/leads/updatecode';
};

export type LeadsPutUpdateCodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsPutUpdateCustomFieldData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Custom Field Id
         */
        id: number;
        /**
         * Lead Id
         */
        leadId: number;
        /**
         * Custom Field Value
         */
        value: string;
    };
    url: '/api/leads/updatecustomfield';
};

export type LeadsPutUpdateCustomFieldResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsGetCustomFieldData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Custom Field Id
         */
        id: number;
        /**
         * Lead Id
         */
        leadId: number;
    };
    url: '/api/leads/getcustomfield';
};

export type LeadsGetCustomFieldResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsPutUpdateCustomFieldsData = {
    /**
     * JSON model of lead custom fields
     */
    body: CustomFieldsUpdateApi;
    path?: never;
    query?: never;
    url: '/api/leads/updatecustomfields';
};

export type LeadsPutUpdateCustomFieldsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsPutMarkAsProcessedData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lead Docket Lead ID
         */
        id: number;
        /**
         * True/False of if it should be marked processed
         */
        markprocessed?: boolean;
    };
    url: '/api/leads/markasprocessed';
};

export type LeadsPutMarkAsProcessedResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLeadsByIdFilesUploadData = {
    body?: never;
    path: {
        /**
         * Lead Docket Lead ID
         */
        id: number;
    };
    query?: {
        /**
         * Name of uploader
         */
        uploadedBy?: string;
        /**
         * Allow creation of duplicate files
         */
        allowDuplicateFilesOnLead?: boolean;
    };
    url: '/api/leads/{id}/files/upload';
};

export type PostApiLeadsByIdFilesUploadResponses = {
    /**
     * OK
     */
    200: LeadFileUploadApi;
};

export type PostApiLeadsByIdFilesUploadResponse = PostApiLeadsByIdFilesUploadResponses[keyof PostApiLeadsByIdFilesUploadResponses];

export type PostApiLeadsByIdFilesGetuploadurlData = {
    body?: never;
    path: {
        /**
         * Lead Docket Lead ID
         */
        id: number;
    };
    query: {
        /**
         * filename with extension
         */
        fileName: string;
        /**
         * Name of uploader
         */
        uploadedBy?: string;
    };
    url: '/api/leads/{id}/files/getuploadurl';
};

export type PostApiLeadsByIdFilesGetuploadurlResponses = {
    /**
     * OK
     */
    200: BlobUrlResponseModel;
};

export type PostApiLeadsByIdFilesGetuploadurlResponse = PostApiLeadsByIdFilesGetuploadurlResponses[keyof PostApiLeadsByIdFilesGetuploadurlResponses];

export type PostApiLeadsByIdFilesByFileIdfinalizeuploadData = {
    body?: never;
    path: {
        /**
         * Lead Docket Lead ID
         */
        id: number;
        /**
         * File ID returned from getuploadurl
         */
        fileId: number;
    };
    query?: never;
    url: '/api/leads/{id}/files/{fileId}finalizeupload';
};

export type PostApiLeadsByIdFilesByFileIdfinalizeuploadResponses = {
    /**
     * OK
     */
    200: LeadFileUploadApi;
};

export type PostApiLeadsByIdFilesByFileIdfinalizeuploadResponse = PostApiLeadsByIdFilesByFileIdfinalizeuploadResponses[keyof PostApiLeadsByIdFilesByFileIdfinalizeuploadResponses];

export type PostApiLeadsByIdFilesByFileIdAssociatefilewithfieldByFieldIdData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        id: number;
        /**
         * Uploaded File Id
         */
        fileId: number;
        /**
         * Custom Field Id
         */
        fieldId: number;
    };
    query?: never;
    url: '/api/leads/{id}/files/{fileId}/associatefilewithfield/{fieldId}';
};

export type PostApiLeadsByIdFilesByFileIdAssociatefilewithfieldByFieldIdResponses = {
    /**
     * OK
     */
    200: LeadFileUploadApi;
};

export type PostApiLeadsByIdFilesByFileIdAssociatefilewithfieldByFieldIdResponse = PostApiLeadsByIdFilesByFileIdAssociatefilewithfieldByFieldIdResponses[keyof PostApiLeadsByIdFilesByFileIdAssociatefilewithfieldByFieldIdResponses];

export type DownloadFileData = {
    body?: never;
    path?: {
        /**
         * File ID
         */
        id?: number;
    };
    query?: never;
    url: '/api/leads/files/download/{id}';
};

export type DownloadFileResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiLeadsByIdNotesData = {
    /**
     * Contains information about the note.
     */
    body: LeadNoteAddApi;
    path: {
        /**
         * The id of the lead for which note is being added.
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/{id}/notes';
};

export type PostApiLeadsByIdNotesResponses = {
    /**
     * Created
     */
    201: LeadNoteApi;
};

export type PostApiLeadsByIdNotesResponse = PostApiLeadsByIdNotesResponses[keyof PostApiLeadsByIdNotesResponses];

export type DeleteApiLeadsByIdNotesByNoteIdData = {
    body?: never;
    path: {
        /**
         * The id of the lead.
         */
        id: number;
        /**
         * The id of the note to delete.
         */
        noteId: number;
    };
    query?: never;
    url: '/api/leads/{id}/notes/{noteId}';
};

export type DeleteApiLeadsByIdNotesByNoteIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiLeadsByIdNotesByNoteIdResponse = DeleteApiLeadsByIdNotesByNoteIdResponses[keyof DeleteApiLeadsByIdNotesByNoteIdResponses];

export type PutApiLeadsByIdNotesByNoteIdData = {
    /**
     * Contains updated information about the note.
     */
    body: LeadNoteUpdateApi;
    path: {
        /**
         * The id of the lead.
         */
        id: number;
        /**
         * The id of the note to update.
         */
        noteId: number;
    };
    query?: never;
    url: '/api/leads/{id}/notes/{noteId}';
};

export type PutApiLeadsByIdNotesByNoteIdResponses = {
    /**
     * OK
     */
    200: LeadNoteApi;
};

export type PutApiLeadsByIdNotesByNoteIdResponse = PutApiLeadsByIdNotesByNoteIdResponses[keyof PutApiLeadsByIdNotesByNoteIdResponses];

export type PatchApiLeadsByIdAppointmentsScheduleData = {
    /**
     * Contains information about the appointment.
     */
    body: ScheduleAppointmentApi;
    path: {
        /**
         * The id of the lead for which appointment is to be scheduled.
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/{id}/appointments/schedule';
};

export type PatchApiLeadsByIdAppointmentsScheduleResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiLeadsByIdStatusChangeData = {
    /**
     * Contains information about changing lead status.
     */
    body: ChangeLeadStatusApi;
    path: {
        /**
         * The id of the lead for which status is being changed.
         */
        id: number;
    };
    query?: never;
    url: '/api/leads/{id}/status/change';
};

export type PatchApiLeadsByIdStatusChangeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiLeadsByIdSubstatusAdvanceData = {
    body?: never;
    path: {
        /**
         * The id of the lead to move.
         */
        id: number;
    };
    query?: {
        /**
         * Current Status ID
         */
        currentStatusId?: number;
        /**
         * Current Substatus ID
         */
        currentSubstatusId?: number;
    };
    url: '/api/leads/{id}/substatus/advance';
};

export type PatchApiLeadsByIdSubstatusAdvanceResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsPostAddRelatedContactData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lead Docket Lead ID
         */
        leadid: number;
        /**
         * Lead Docket Contact ID
         */
        contactid: number;
        /**
         * Relationship to the lead
         */
        relationship: string;
        /**
         * Is this an additional plaintiff
         */
        additionalplaintiff?: boolean;
    };
    url: '/api/leads/addrelatedcontact';
};

export type LeadsPostAddRelatedContactResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type LeadsPatchUpdateLeadRoleUserData = {
    body?: never;
    path?: never;
    query: {
        leadid: number;
        leadRoleId: number;
        assignToUserId: number;
    };
    url: '/api/leads/updateleadroleuser';
};

export type LeadsPatchUpdateLeadRoleUserResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLeadsourcesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/leadsources/list';
};

export type GetApiLeadsourcesListResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLookupsGettypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/lookups/gettypes';
};

export type GetApiLookupsGettypesResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiLookupsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The type of lookup data to retrieve
         */
        type: LookupTypes;
    };
    url: '/api/lookups';
};

export type GetApiLookupsResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostApiMessagesData = {
    /**
     * Contains information about the message to be created.
     */
    body: MessageAddApi;
    path?: never;
    query?: never;
    url: '/api/messages';
};

export type PostApiMessagesResponses = {
    /**
     * Created
     */
    201: MessageApi;
};

export type PostApiMessagesResponse = PostApiMessagesResponses[keyof PostApiMessagesResponses];

export type PostApiMessagesSendtextData = {
    /**
     * Contains information about the text message to be sent.
     * SendFrom is optional. If it is not provided the message will send from the lead default SMS number.
     */
    body: SendTextMessageApi;
    path?: never;
    query?: never;
    url: '/api/messages/sendtext';
};

export type PostApiMessagesSendtextResponses = {
    /**
     * Created
     */
    201: MessageApi;
};

export type PostApiMessagesSendtextResponse = PostApiMessagesSendtextResponses[keyof PostApiMessagesSendtextResponses];

export type PostApiMessagesSendemailData = {
    /**
     * Contains information about the email message to be sent.
     * SendTo is required and must be the email address of a lead contact.
     * SendFrom is required and must be the email address of a lead role user assigned to this lead.
     * SendFromName is optional
     */
    body: SendEmailMessageApi;
    path?: never;
    query?: never;
    url: '/api/messages/sendemail';
};

export type PostApiMessagesSendemailResponses = {
    /**
     * Created
     */
    201: MessageApi;
};

export type PostApiMessagesSendemailResponse = PostApiMessagesSendemailResponses[keyof PostApiMessagesSendemailResponses];

export type OpportunitiesGetOpportunityByIdData = {
    body?: never;
    path: {
        /**
         * Opportunity Id
         */
        id: number;
    };
    query?: never;
    url: '/api/opportunities/{id}';
};

export type OpportunitiesGetOpportunityByIdResponses = {
    /**
     * OK
     */
    200: OpportunityApi;
};

export type OpportunitiesGetOpportunityByIdResponse = OpportunitiesGetOpportunityByIdResponses[keyof OpportunitiesGetOpportunityByIdResponses];

export type OpportunitiesGetCreatedSinceData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opportunities created since this date.
         */
        date?: string;
        /**
         * Page of the record set. Defaults to 1 if not specified.
         */
        page?: number;
        /**
         * Number of items per paged request. Maximum is 500, defaults to 500 if not specified.
         */
        itemsPerPage?: number;
    };
    url: '/api/opportunities/createdsince';
};

export type OpportunitiesGetCreatedSinceResponses = {
    /**
     * OK
     */
    200: OpportunityApiFlatApiPagedResponse;
};

export type OpportunitiesGetCreatedSinceResponse = OpportunitiesGetCreatedSinceResponses[keyof OpportunitiesGetCreatedSinceResponses];

export type OpportunitiesGetLastUpdatedSinceData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Opportunities last updated since this date.
         */
        date?: string;
        /**
         * Page of the record set. Defaults to 1 if not specified.
         */
        page?: number;
        /**
         * Number of items per paged request. Maximum is 500, defaults to 500 if not specified.
         */
        itemsPerPage?: number;
    };
    url: '/api/opportunities/lastupdatedsince';
};

export type OpportunitiesGetLastUpdatedSinceResponses = {
    /**
     * OK
     */
    200: OpportunityApiFlatApiPagedResponse;
};

export type OpportunitiesGetLastUpdatedSinceResponse = OpportunitiesGetLastUpdatedSinceResponses[keyof OpportunitiesGetLastUpdatedSinceResponses];

export type OpportunitiesGetListUnprocessedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/opportunities/getlistunprocessed';
};

export type OpportunitiesGetListUnprocessedResponses = {
    /**
     * OK
     */
    200: Array<OpportunityApiFlat>;
};

export type OpportunitiesGetListUnprocessedResponse = OpportunitiesGetListUnprocessedResponses[keyof OpportunitiesGetListUnprocessedResponses];

export type OpportunitiesAppendNoteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Opportunity Id
         */
        opportunityId: number;
        /**
         * Note text to add
         */
        note: string;
    };
    url: '/api/opportunities/appendnote';
};

export type OpportunitiesAppendNoteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type OpportunitiesClearNoteData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Opportunity Id
         */
        opportunityId: number;
    };
    url: '/api/opportunities/clearnote';
};

export type OpportunitiesClearNoteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type OpportunitiesDisregardData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Opportunity Id
         */
        id: number;
        /**
         * Disregard Reason
         */
        reason: string;
    };
    url: '/api/opportunities/disregard';
};

export type OpportunitiesDisregardResponses = {
    /**
     * OK
     */
    200: OpportunityApi;
};

export type OpportunitiesDisregardResponse = OpportunitiesDisregardResponses[keyof OpportunitiesDisregardResponses];

export type OpportunitiesLockData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Opportunity Id
         */
        id: number;
    };
    url: '/api/opportunities/lock';
};

export type OpportunitiesLockResponses = {
    /**
     * OK
     */
    200: OpportunityApi;
};

export type OpportunitiesLockResponse = OpportunitiesLockResponses[keyof OpportunitiesLockResponses];

export type OpportunitiesUnlockData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Opportunity Id
         */
        id: number;
    };
    url: '/api/opportunities/unlock';
};

export type OpportunitiesUnlockResponses = {
    /**
     * OK
     */
    200: OpportunityApi;
};

export type OpportunitiesUnlockResponse = OpportunitiesUnlockResponses[keyof OpportunitiesUnlockResponses];

export type ReferralsDeleteData = {
    body?: never;
    path: {
        /**
         * Lead Docket Referral ID
         */
        id: number;
    };
    query?: never;
    url: '/api/referrals/{id}';
};

export type ReferralsDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReferralsGetByIdData = {
    body?: never;
    path: {
        /**
         * Referral Source Id
         */
        id: number;
    };
    query?: never;
    url: '/api/referrals/{id}';
};

export type ReferralsGetByIdResponses = {
    /**
     * OK
     */
    200: ReferralSourceApi;
};

export type ReferralsGetByIdResponse = ReferralsGetByIdResponses[keyof ReferralsGetByIdResponses];

export type ReferralsEditData = {
    /**
     * JSON model of referral source details to edit
     */
    body: ReferralSourceAddApi;
    path: {
        /**
         * Lead Docket Referral ID
         */
        id: number;
    };
    query?: never;
    url: '/api/referrals/{id}';
};

export type ReferralsEditResponses = {
    /**
     * OK
     */
    200: ReferralSourceApi;
};

export type ReferralsEditResponse = ReferralsEditResponses[keyof ReferralsEditResponses];

export type ReferralsGetByExternalCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * ExternalCode
         */
        externalCode: string;
    };
    url: '/api/referrals/getbyexternalcode';
};

export type ReferralsGetByExternalCodeResponses = {
    /**
     * OK
     */
    200: ReferralSourceApi;
};

export type ReferralsGetByExternalCodeResponse = ReferralsGetByExternalCodeResponses[keyof ReferralsGetByExternalCodeResponses];

export type ReferralsGetListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/referrals/list';
};

export type ReferralsGetListResponses = {
    /**
     * OK
     */
    200: Array<ReferralSourceApi>;
};

export type ReferralsGetListResponse = ReferralsGetListResponses[keyof ReferralsGetListResponses];

export type ReferralsUpdateCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lead Docket Referral ID
         */
        id: number;
        /**
         * Case Tracker Code from external system
         */
        code: string;
    };
    url: '/api/referrals/updatecode';
};

export type ReferralsUpdateCodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReferralsUpdateExternalCodeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Lead Docket Referral ID
         */
        id: number;
        /**
         * Code from external system
         */
        externalCode: string;
    };
    url: '/api/referrals/updateexternalcode';
};

export type ReferralsUpdateExternalCodeResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ReferralGroupsGetListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/referrals/listgroups';
};

export type ReferralGroupsGetListResponses = {
    /**
     * OK
     */
    200: Array<ReferralGroupApi>;
};

export type ReferralGroupsGetListResponse = ReferralGroupsGetListResponses[keyof ReferralGroupsGetListResponses];

export type ReferralsAddData = {
    /**
     * JSON model of referral source details to add
     */
    body: ReferralSourceAddApi;
    path?: never;
    query?: never;
    url: '/api/referrals';
};

export type ReferralsAddResponses = {
    /**
     * OK
     */
    200: ReferralSourceAddApi;
};

export type ReferralsAddResponse = ReferralsAddResponses[keyof ReferralsAddResponses];

export type ReferralsPracticeAreasData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/referrals/listpracticeareas';
};

export type ReferralsPracticeAreasResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type ReferralsPracticeAreasResponse = ReferralsPracticeAreasResponses[keyof ReferralsPracticeAreasResponses];

export type SettingsGetOptionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/settings/get-options';
};

export type SettingsGetOptionsResponses = {
    /**
     * OK
     */
    200: SettingsOptions;
};

export type SettingsGetOptionsResponse = SettingsGetOptionsResponses[keyof SettingsGetOptionsResponses];

export type SettlementsGetSettlementData = {
    body?: never;
    path: {
        /**
         * Settlement Id
         */
        id: number;
    };
    query?: never;
    url: '/api/settlements/{id}';
};

export type SettlementsGetSettlementResponses = {
    /**
     * OK
     */
    200: SettlementApi;
};

export type SettlementsGetSettlementResponse = SettlementsGetSettlementResponses[keyof SettlementsGetSettlementResponses];

export type GetSettlementsByLeadIdData = {
    body?: never;
    path: {
        /**
         * Lead Id
         */
        id: number;
    };
    query?: never;
    url: '/api/settlements/getbyleadid/{id}';
};

export type GetSettlementsByLeadIdResponses = {
    /**
     * OK
     */
    200: SettlementApi;
};

export type GetSettlementsByLeadIdResponse = GetSettlementsByLeadIdResponses[keyof GetSettlementsByLeadIdResponses];

export type AddSettlementData = {
    /**
     * The settlement information.
     */
    body: SettlementAddApi;
    path?: never;
    query?: never;
    url: '/api/settlements';
};

export type AddSettlementResponses = {
    /**
     * Created
     */
    201: SettlementApi;
};

export type AddSettlementResponse = AddSettlementResponses[keyof AddSettlementResponses];

export type StatusesGetByIdData = {
    body?: never;
    path: {
        /**
         * Status Id
         */
        id: number;
    };
    query?: never;
    url: '/api/statuses/{id}';
};

export type StatusesGetByIdResponses = {
    /**
     * OK
     */
    200: StatusApiApiHypermedia;
};

export type StatusesGetByIdResponse = StatusesGetByIdResponses[keyof StatusesGetByIdResponses];

export type StatusUpdateData = {
    /**
     * details to update on the LeadDocket.Core.Models.Status. note - only the data provided will be updated.
     */
    body: StatusUpdateApi;
    path: {
        /**
         * ID of the LeadDocket.Core.Models.Status
         */
        id: number;
    };
    query?: never;
    url: '/api/statuses/{id}';
};

export type StatusUpdateResponses = {
    /**
     * OK
     */
    200: StatusApiApiHypermedia;
};

export type StatusUpdateResponse = StatusUpdateResponses[keyof StatusUpdateResponses];

export type StatusesGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/statuses';
};

export type StatusesGetAllResponses = {
    /**
     * OK
     */
    200: StatusApiApiHypermediaListApiHypermedia;
};

export type StatusesGetAllResponse = StatusesGetAllResponses[keyof StatusesGetAllResponses];

export type StatusCreateData = {
    /**
     * details to populate the new LeadDocket.Core.Models.Status
     */
    body: StatusCreateApi;
    path?: never;
    query: {
        /**
         * The LeadDocket.Core.Models.Api.Request.CreateStatusRecipe value for this LeadDocket.Core.Models.Status
         */
        type: CreateStatusRecipe;
    };
    url: '/api/statuses';
};

export type StatusCreateResponses = {
    /**
     * Created
     */
    201: StatusCreateApiApiHypermedia;
};

export type StatusCreateResponse = StatusCreateResponses[keyof StatusCreateResponses];

export type SubStatusCreateData = {
    /**
     * details to populate the new LeadDocket.Core.Models.Substatus(es)
     */
    body: Array<SubStatusCreateApi>;
    path: {
        /**
         * Id of the LeadDocket.Core.Models.Status
         */
        statusId: number;
    };
    query?: never;
    url: '/api/statuses/{statusId}/substatus';
};

export type SubStatusCreateResponses = {
    /**
     * Created
     */
    201: StatusApiApiHypermedia;
};

export type SubStatusCreateResponse = SubStatusCreateResponses[keyof SubStatusCreateResponses];

export type SubStatusUpdateData = {
    /**
     * details to update on the LeadDocket.Core.Models.Substatus. note - only the data provided will be updated.
     */
    body: SubStatusUpdateApi;
    path: {
        /**
         * ID of the LeadDocket.Core.Models.Status which the LeadDocket.Core.Models.Substatus is associated with
         */
        statusId: number;
        /**
         * ID of the LeadDocket.Core.Models.Substatus being updated
         */
        subStatusId: number;
    };
    query?: never;
    url: '/api/statuses/{statusId}/substatus/{subStatusId}';
};

export type SubStatusUpdateResponses = {
    /**
     * OK
     */
    200: StatusApiApiHypermedia;
};

export type SubStatusUpdateResponse = SubStatusUpdateResponses[keyof SubStatusUpdateResponses];

export type SubstatusDeleteData = {
    body?: never;
    path: {
        /**
         * ID of the LeadDocket.Core.Models.Status which the LeadDocket.Core.Models.Substatus is associated with
         */
        statusId: number;
        /**
         * ID of the LeadDocket.Core.Models.Substatus being updated
         */
        substatusId: number;
    };
    query?: never;
    url: '/api/statuses/{statusId}/substatus/{substatusId}';
};

export type SubstatusDeleteResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type DeleteApiTasksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type DeleteApiTasksByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTasksByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tasks/{id}';
};

export type GetApiTasksByIdResponses = {
    /**
     * OK
     */
    200: TaskApi;
};

export type GetApiTasksByIdResponse = GetApiTasksByIdResponses[keyof GetApiTasksByIdResponses];

export type GetApiTasksLeadsByLeadIdData = {
    body?: never;
    path: {
        leadId: number;
    };
    query?: never;
    url: '/api/tasks/leads/{leadId}';
};

export type GetApiTasksLeadsByLeadIdResponses = {
    /**
     * OK
     */
    200: Array<TaskApi>;
};

export type GetApiTasksLeadsByLeadIdResponse = GetApiTasksLeadsByLeadIdResponses[keyof GetApiTasksLeadsByLeadIdResponses];

export type TaskAddData = {
    body: TaskCreateApi;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type TaskAddResponses = {
    /**
     * OK
     */
    200: TaskApi;
};

export type TaskAddResponse = TaskAddResponses[keyof TaskAddResponses];

export type PutApiTasksData = {
    body: TaskUpdateApi;
    path?: never;
    query?: never;
    url: '/api/tasks';
};

export type PutApiTasksResponses = {
    /**
     * OK
     */
    200: TaskApi;
};

export type PutApiTasksResponse = PutApiTasksResponses[keyof PutApiTasksResponses];

export type PutApiTasksMarkcompleteByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/tasks/markcomplete/{id}';
};

export type PutApiTasksMarkcompleteByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type UsersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/users';
};

export type UsersListResponses = {
    /**
     * OK
     */
    200: Array<UserApi>;
};

export type UsersListResponse = UsersListResponses[keyof UsersListResponses];

export type UserByIdData = {
    body?: never;
    path: {
        /**
         * Lead Docket User ID
         */
        id: number;
    };
    query?: never;
    url: '/api/users/{id}';
};

export type UserByIdResponses = {
    /**
     * OK
     */
    200: UserApi;
};

export type UserByIdResponse = UserByIdResponses[keyof UserByIdResponses];

export type UsersByRoleData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Role ID from /api/leadroles
         */
        leadRoleId: number;
    };
    url: '/api/users/byrole';
};

export type UsersByRoleResponses = {
    /**
     * OK
     */
    200: Array<UserApi>;
};

export type UsersByRoleResponse = UsersByRoleResponses[keyof UsersByRoleResponses];

export type UserByCodeData = {
    body?: never;
    path: {
        /**
         * Case Tracker Code
         */
        code: string;
    };
    query?: never;
    url: '/api/users/getuserbycode/{code}';
};

export type UserByCodeResponses = {
    /**
     * OK
     */
    200: UserApi;
};

export type UserByCodeResponse = UserByCodeResponses[keyof UserByCodeResponses];

export type UserByFilevineUserIdData = {
    body?: never;
    path: {
        /**
         * Filevine User ID
         */
        id: number;
    };
    query?: never;
    url: '/api/users/getuserbyfilevineuserid/{id}';
};

export type UserByFilevineUserIdResponses = {
    /**
     * OK
     */
    200: UserApi;
};

export type UserByFilevineUserIdResponse = UserByFilevineUserIdResponses[keyof UserByFilevineUserIdResponses];
